#!/usr/bin/env python3
"""Every basis declaration the corpus triggers, with the rule that fired and the
sentence it fired on.

Why this exists. Round 53 introduced ``pyd_basis_rule``: the extraction models'
own statements about whether the recorded prior-year development figure is gross
or net, read before the prompt's gross default applies. A rule demonstrated on the
three audited donors is a lexical gate until it is shown on the whole corpus, so
this script applies ``run_analysis.pyd_basis`` to every corpus record exactly as
the loader does and writes each declaration it finds: the record, the recorded
figure, the verdict, the pattern that matched and the sentence. The Markdown table
lists the verdicts that keep a figure out of the gross sample (net, inconsistent,
unstated); the JSON carries every declaration, gross ones included.

Reads:   pdf_extraction/syndicate_*.json, data/pyd_basis_register.json
Writes:  results/pyd_basis_declarations.json, results/pyd_basis_declarations.md

Run:  python src/audit_pyd_basis.py
"""
import collections
import io
import json
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
import sys  # noqa: E402
sys.path.insert(0, os.path.join(HERE, "src"))
import run_analysis as ra  # noqa: E402
import pyd_basis_rule as rule  # noqa: E402

PYD = os.path.join(HERE, "pdf_extraction")
OUT_JSON = os.path.join(HERE, "results", "pyd_basis_declarations.json")
OUT_MD = os.path.join(HERE, "results", "pyd_basis_declarations.md")


def canonical_block(d):
    """The block run_analysis reads as the record's figure (its own selection rule)."""
    models = d.get("models") or {}
    keys = sorted(models)
    if not keys:
        return None, None
    if (d.get("validation") or {}).get("passed") is True:
        return keys[0], models[keys[0]]
    cand = [(k, models[k].get("prior_year_movement_confidence", 0) or 0)
            for k in keys if models[k].get("prior_year_development_pct") is not None]
    if not cand:
        return None, None
    ck = cand[0][0] if len(cand) == 1 else max(cand, key=lambda x: x[1])[0]
    return ck, models[ck]


def main():
    register = ra.load_pyd_basis_register()
    rows = []
    for fn in sorted(os.listdir(PYD)):
        if not (fn.startswith("syndicate_") and fn.endswith(".json")):
            continue
        d = json.load(io.open(os.path.join(PYD, fn), encoding="utf-8"))
        ck, cm = canonical_block(d)
        if cm is None:
            continue
        key = "%s_%s" % (cm.get("syndicate", d.get("syndicate")), cm.get("year", d.get("year")))
        pyd = ra.safe_float(cm.get("prior_year_development_gbp_m"))
        basis, source, evidence = ra.pyd_basis(cm, key, register, d.get("models"))
        verdict, quote, who, which = rule.record_declaration_detail(d.get("models") or {}, pyd)
        if verdict is None:
            continue
        rows.append({"record": key, "file": fn, "recorded_gbp_m": pyd, "declaration": verdict,
                     "rule": which, "model": who, "sentence": quote,
                     "basis_assigned": basis, "basis_source": source})
    by_rule = collections.Counter(r["rule"] for r in rows)
    by_verdict = collections.Counter(r["declaration"] for r in rows)
    keep_out = [r for r in rows if r["declaration"] in rule.NOT_GROSS]
    # where a keep-out declaration nevertheless ends gross, the step that assigned it
    # (a pipeline override carrying a gross triangle, or a register decision)
    gross_despite = collections.Counter(r["basis_source"].split(":")[0]
                                        for r in keep_out if r["basis_assigned"] == "gross")
    keep_out_basis = collections.Counter(r["basis_assigned"] for r in keep_out)
    out = {"purpose": __doc__.split("\n\n")[0].strip(),
           "n_records_with_a_declaration": len(rows),
           "by_declaration": dict(by_verdict), "by_rule": dict(sorted(by_rule.items())),
           "keep_out_by_assigned_basis": dict(keep_out_basis),
           "keep_out_ending_gross_by_source": dict(gross_despite),
           "patterns": {"net": rule._DECLARED_NET, "unstated": rule._DECLARED_UNSTATED,
                        "gross": rule._DECLARED_GROSS},
           "declarations": rows}
    json.dump(out, io.open(OUT_JSON, "w", encoding="utf-8", newline="\n"), indent=1)

    lines = ["# Basis declarations read from the extraction models",
             "",
             "Generated by `src/audit_pyd_basis.py`; do not edit. Every corpus record whose "
             "model blocks declare the basis of the recorded prior-year development figure, "
             "with the pattern that matched. This table lists the declarations that keep a "
             "figure out of the gross sample; the JSON beside it carries all %d, gross "
             "declarations included." % len(rows),
             "",
             "| Declaration | Records |", "|---|---|"]
    lines += ["| %s | %d |" % (k, v) for k, v in sorted(by_verdict.items())]
    lines += ["", "| Rule | Records |", "|---|---|"]
    lines += ["| `%s` | %d |" % (k, v) for k, v in sorted(by_rule.items())]
    lines += ["",
              "Of the %d keep-out declarations, the loader assigns %s. A keep-out declaration "
              "ends gross only where an earlier step of the loader settles the basis: %s. "
              "The 'Basis source' column names that step for every row; 'declared-*' means "
              "the declaration itself decided." % (
                  len(keep_out),
                  ", ".join("%d %s" % (v, k) for k, v in sorted(keep_out_basis.items())),
                  ", ".join("%d by %s" % (v, k) for k, v in sorted(gross_despite.items())) or "none"),
              "",
              "| Record | Recorded (m) | Declaration | Rule | Assigned basis | Basis source | Sentence |",
              "|---|---|---|---|---|---|---|"]
    for r in keep_out:
        s = (r["sentence"] or "").replace("|", "\\|")
        lines.append("| %s | %s | %s | `%s` | %s | %s | %s |" % (
            r["record"], "" if r["recorded_gbp_m"] is None else "%.3f" % r["recorded_gbp_m"],
            r["declaration"], r["rule"], r["basis_assigned"], r["basis_source"].split(":")[0], s[:220]))
    io.open(OUT_MD, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print("declarations: %d records; %s; rules %s" % (len(rows), dict(by_verdict), dict(by_rule)))


if __name__ == "__main__":
    main()
