#!/usr/bin/env python3
"""The error-rate propagation, re-run on the current fit (src/error_rate_propagation.py).

The extraction error-rate study simulated its unfound errors onto Vignette 1's VaR99.5 once, on a 685-record
fit, and the manuscript said it ran on the final fit (review of 29 September 2026, M-3). The manifest step
now re-runs it on the fit in the tree. These tests hold it to the study (its constants, read from the
archive's own script; its inputs, read from the archive), to itself (seeded, and a pool with nothing unread
cannot move), and to the headline it perturbs: it refuses unless that is vignette_uncertainty's own centre
under the same operator, and it records the fit it ran on.

Run:  python -m pytest src/test_error_rate_propagation.py -q
"""
import ast
import io
import json
import os

import numpy as np
import pytest

import error_rate_propagation as E
import transfer_operator as TO
import vignette_uncertainty as vu

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ARCHIVE_SCRIPT = os.path.join(HERE, "results", "extraction_error_rate", "scripts", "error_rate_propagation.py")


def _module_constants(path):
    tree = ast.parse(io.open(path, encoding="utf-8").read())
    out = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            try:
                out[node.targets[0].id] = ast.literal_eval(node.value)
            except ValueError:
                pass
    return out


def test_the_constants_are_the_studys_own():
    if not os.path.exists(ARCHIVE_SCRIPT):
        pytest.skip("results/extraction_error_rate/scripts/error_rate_propagation.py not present in this checkout")
    study = _module_constants(ARCHIVE_SCRIPT)
    assert (study["SEED"], study["M"], study["MATERIAL"]) == (E.SEED, E.M, E.MATERIAL)


def test_the_inputs_are_the_archives():
    inp = E.inputs()
    assert (inp["errors"], inp["adjudicable"]) == (8, 162), "the third sample's A_sampled record"
    assert len(inp["shifts"]) == len(inp["confirmed"]) > 0 and np.all(np.isfinite(inp["shifts"]))
    assert inp["read"] and all(s.startswith("syndicate_") for s in inp["read"])


@pytest.fixture(scope="module")
def pool():
    S, R, H, synd, year = vu.load_pool()
    draws, ref, hlo, hce = vu.load_draws()
    ritc = vu.load_ritc(synd, year)
    v1, _o, _n = vu.load_targets()
    thbar = TO.params({p: float(draws[p].mean()) for p in draws}, TO.HEADLINE)
    return S, R, H, ritc, thbar, (ref, hlo, hce), v1


def test_the_simulation_is_seeded(pool):
    S, R, H, ritc, thbar, cfg, v1 = pool
    unread = np.arange(0, len(S), 2)
    shifts = np.array([0.05, -0.02, 0.1])
    a = E.propagate(S, R, H, ritc, thbar, cfg, v1, unread, shifts, 8.5, 154.5, m=12, seed=3)
    b = E.propagate(S, R, H, ritc, thbar, cfg, v1, unread, shifts, 8.5, 154.5, m=12, seed=3)
    c = E.propagate(S, R, H, ritc, thbar, cfg, v1, unread, shifts, 8.5, 154.5, m=12, seed=4)
    assert a == b and a != c


def test_with_every_record_read_nothing_moves(pool):
    S, R, H, ritc, thbar, cfg, v1 = pool
    out = E.propagate(S, R, H, ritc, thbar, cfg, v1, np.array([], int), np.array([0.05]), 8.5, 154.5, m=10, seed=1)
    for setting in ("p_from_posterior", "p_at_posterior_97_5"):
        assert out[setting]["K"]["mean"] == 0.0
        for mm in E.MODELS:
            assert out[setting][mm]["P_abs_relative_change_gt_5pct"] == 0.0
            assert out[setting][mm]["change"]["median"] == 0.0


def test_the_base_is_the_headline_centre(pool):
    S, R, H, ritc, thbar, cfg, v1 = pool
    out = E.propagate(S, R, H, ritc, thbar, cfg, v1, np.array([0, 1]), np.array([0.05]), 8.5, 154.5, m=2, seed=1)
    assert out["V1_VaR995"] == vu.var_q(vu.transfer(S, R, H, v1, thbar, cfg, ritc), 0.995)
    assert thbar["gamma"] == 0.0


# ------------------------------------------------------------------ main(), small ------
@pytest.fixture
def small_main(monkeypatch, tmp_path):
    """main() with 5 replicates, writing to tmp_path and checking against a vignette record written there."""
    real = E.propagate
    monkeypatch.setattr(E, "propagate", lambda *a, **k: real(*a, **dict(k, m=5)))
    monkeypatch.setattr(E, "OUT", tmp_path / "error_rate_propagation_results.json")
    # the loader's output as the current loader writes it: the committed file is regenerated by the recorded pass, so
    # it may not carry the calibration-free run id yet
    ex = json.load(io.open(str(E.EXPOSURE), encoding="utf-8"))
    ex.setdefault("analysis_run_id_without_calibration", "run-without-calibration-for-the-test")
    ex_path = tmp_path / "exposure_results.json"
    ex_path.write_text(json.dumps(ex), encoding="utf-8")
    monkeypatch.setattr(E, "EXPOSURE", ex_path)
    monkeypatch.setattr(vu, "B", 8)
    record, _prim, _centres = vu.compute()
    vu_path = tmp_path / "vignette_uncertainty_results.json"

    def write_vu(rec):
        vu_path.write_text(json.dumps(rec), encoding="utf-8")
        monkeypatch.setattr(E, "VU", vu_path)

    return record, write_vu, E.OUT


def test_main_writes_both_operators_and_the_fit_it_ran_on(small_main):
    record, write_vu, out = small_main
    write_vu(record)
    assert E.main() == 0
    res = json.load(io.open(str(out), encoding="utf-8"))
    assert (res["operator"], res["operator_role"]) == ("size_only", "headline")
    assert res["overlay_sensitivity"]["operator"] == "overlay"
    assert res["V1_VaR995"] == record["centres_full_pool_posterior_mean"]["V1_adj"]["v995"]
    assert res["fit"]["n_working_sample"] == len(vu.load_pool()[0])
    ex = json.load(io.open(str(E.EXPOSURE), encoding="utf-8"))
    assert res["fit"]["loader_run_id_without_calibration"] == ex["analysis_run_id_without_calibration"]
    current = res["rate_population"]["current"]
    assert current["exposure_results_run_id_without_calibration"] == ex["analysis_run_id_without_calibration"]
    assert "loader_run_id" not in res["fit"]
    import subprocess
    head = subprocess.run(["git", "-C", HERE, "rev-parse", "HEAD"], capture_output=True, text=True)
    assert res["fit"]["analysis_commit"] == ((head.stdout.strip() or None) if head.returncode == 0 else None)
    assert isinstance(res["fit"]["tree_dirty_src_model_results"], bool)
    pm = res["per_model"]
    assert set(pm["P_abs_relative_change_gt_5pct"]) == set(E.MODELS)
    assert len(pm["shift_model_relative_change"]["interval_95"]) == 2


def test_main_refuses_a_loader_output_without_the_calibration_free_run_id(small_main, monkeypatch, tmp_path):
    """A model/exposure_results.json written before the field existed cannot bind the fit to the loader's run."""
    record, write_vu, out = small_main
    write_vu(record)
    ex = json.load(io.open(str(E.EXPOSURE), encoding="utf-8"))
    del ex["analysis_run_id_without_calibration"]
    stale = tmp_path / "stale_exposure_results.json"
    stale.write_text(json.dumps(ex), encoding="utf-8")
    monkeypatch.setattr(E, "EXPOSURE", stale)
    with pytest.raises(SystemExit):
        E.main()
    assert not out.exists()


@pytest.mark.parametrize("plant", ["wrong_centre", "no_operator"])
def test_main_refuses_a_headline_that_is_not_the_vignette_records(small_main, plant):
    record, write_vu, out = small_main
    rec = json.loads(json.dumps(record))
    if plant == "wrong_centre":
        rec["centres_full_pool_posterior_mean"]["V1_adj"]["v995"] += 1e-6
    else:
        del rec["operator"]
    write_vu(rec)
    with pytest.raises(SystemExit):
        E.main()
    assert not out.exists()


def test_the_run_state_it_records_is_volatile_for_the_verifier():
    """The fit record names the commit the step ran at and whether src, model or results differed from it then.
    A recorded pass starts from a commit that already holds the outputs, so it always runs at a later commit than
    the run that wrote them: neither value can reproduce, and the verifier must exclude both, as it excludes the
    vignette metadata's git_commit_or_hash (round 62: the first recorded pass after this step joined the manifest
    would otherwise have failed on this file). The content identifiers of the fit must still count."""
    import sys
    sys.path.insert(0, HERE)
    import reproduce
    run_state = {"analysis_commit", "tree_dirty_src_model_results"}
    fit = E.fit_record()
    assert run_state <= set(fit)
    assert run_state <= set(reproduce.VOLATILE)
    assert not (set(fit) - run_state) & set(reproduce.VOLATILE)

    def canon(record):
        return reproduce.canonical_json_sha256(json.dumps({"fit": record}).encode("utf-8"))

    other_run = dict(fit, analysis_commit="0" * 40,
                     tree_dirty_src_model_results=not fit["tree_dirty_src_model_results"])
    assert canon(other_run) == canon(fit)
    assert canon(dict(fit, n_working_sample=fit["n_working_sample"] + 1)) != canon(fit)
    assert canon(dict(fit, loader_run_id_without_calibration="another-run")) != canon(fit)


def test_the_archive_readme_points_at_the_current_fit_record():
    """Round 62's verification: the error-rate archive's README called the 5b31803 run "the final fit" and did not
    point at the current fit's record, whose figures differ (0.941 against its 0.932)."""
    readme = io.open(os.path.join(HERE, "results", "extraction_error_rate", "README.md"), encoding="utf-8").read()
    flat = " ".join(readme.split())
    assert "on the final fit" not in flat
    assert "`results/error_rate_propagation_results.json`" in flat and "`src/error_rate_propagation.py`" in flat
    assert "not the current fit's" in flat


def test_the_recorded_run_is_bound_to_the_loaders_run_and_its_own_detail():
    """Round 62's verification: the recorded file's loader_run_id retyped (E3) and a per-model probability retyped
    (E4) both passed. The run it names must be the loader's own run in model/exposure_results.json; each per-model
    probability must be the detail block's, a whole number of replicates; and the unread and read records must add
    up to the working sample the fit names."""
    path = os.path.join(HERE, "results", "error_rate_propagation_results.json")
    if not os.path.exists(path):
        pytest.skip("results/error_rate_propagation_results.json not present in this checkout")
    res = json.load(io.open(path, encoding="utf-8"))
    ex = json.load(io.open(os.path.join(HERE, "model", "exposure_results.json"), encoding="utf-8"))
    assert "analysis_run_id_without_calibration" in ex, (
        "model/exposure_results.json predates the calibration-free run id: the recorded pass regenerates it")
    # the calibration-free ids, not the full run ids: the loader pass and the outputs pass load different
    # calibrations, so the full id the fit saw (the loader pass's) differs from the one the outputs pass writes
    assert res["fit"]["loader_run_id_without_calibration"] == ex["analysis_run_id_without_calibration"]
    current = res["rate_population"]["current"]
    assert current["exposure_results_run_id_without_calibration"] == ex["analysis_run_id_without_calibration"]
    assert res["fit"]["n_working_sample"] == ex["disposition_flow"]["working_sample"]
    assert res["unread_working_sample_records"] + res["read_records_in_pool"] == res["fit"]["n_working_sample"]
    per = res["per_model"]
    for m in E.MODELS:
        for summary, detail in (("P_abs_relative_change_gt_5pct", res["p_from_posterior"]),
                                ("P_abs_relative_change_gt_5pct_at_rate_97_5", res["p_at_posterior_97_5"])):
            p = per[summary][m]
            assert p == detail[m]["P_abs_relative_change_gt_5pct"], (summary, m)
            assert abs(p * res["replicates"] - round(p * res["replicates"])) < 1e-6, (summary, m, p)
    shift = res["p_from_posterior"]["shift"]["relative_change"]
    assert per["shift_model_relative_change"]["median"] == shift["median"]
    assert per["shift_model_relative_change"]["interval_95"] == [shift["p2_5"], shift["p97_5"]]


def test_the_recorded_run_is_on_the_current_fit():
    """DEFERRED-TO-REFIT: results/error_rate_propagation_results.json is written by the recorded pass."""
    path = os.path.join(HERE, "results", "error_rate_propagation_results.json")
    if not os.path.exists(path):
        pytest.skip("results/error_rate_propagation_results.json not present in this checkout")
    res = json.load(io.open(path, encoding="utf-8"))
    head = json.load(io.open(os.path.join(HERE, "results", "vignette_uncertainty_results.json"), encoding="utf-8"))
    assert res["operator"] == head["operator"] == TO.HEADLINE
    assert res["V1_VaR995"] == head["centres_full_pool_posterior_mean"]["V1_adj"]["v995"]
    assert res["fit"]["n_working_sample"] == head["meta"]["n_donors"]
    assert (res["replicates"], res["seed"], res["materiality_line_relative"]) == (E.M, E.SEED, E.MATERIAL)


def _rate(verdicts, run_id="run-drawn", n=5):
    return {"exposure_results_run_id": run_id, "working_sample": {"A_n": n}, "final_verdicts": {"A": verdicts}}


def test_the_rate_population_counts_the_sampled_records_still_in_the_working_sample():
    """P-3 (the review of 2 October 2026): the sampled records were drawn from an earlier working sample; the
    result names that run and gives the verdicts and the rate of the records still in the current one."""
    rate = _rate({"syndicate_1_2020": "error", "syndicate_2_2020": "correct", "syndicate_3_2020": "error",
                  "syndicate_4_2020": "undeterminable", "syndicate_5_2020": "correct"})
    out = E.rate_population(rate, ["syndicate_1_2020", "syndicate_2_2020", "syndicate_4_2020", "syndicate_9_2020"],
                            "run-now")
    assert out["drawn_from"] == {"exposure_results_run_id": "run-drawn", "working_sample_n": 5}
    assert out["current"] == {"exposure_results_run_id_without_calibration": "run-now", "working_sample_n": 4}
    assert out["same_population"] is False
    assert (out["n_sampled"], out["n_in_current_working_sample"], out["n_left_current_working_sample"]) == (5, 3, 2)
    assert out["left_current_working_sample"] == [{"stem": "syndicate_3_2020", "verdict": "error"},
                                                  {"stem": "syndicate_5_2020", "verdict": "correct"}]
    assert out["verdicts_in_current_working_sample"] == {"error": 1, "correct": 1, "undeterminable": 1}
    post = out["posterior_in_current_working_sample"]
    assert (post["alpha"], post["beta"]) == (1.5, 1.5) and post["mean"] == pytest.approx(0.5)
    lo, hi = post["ci95_equal_tailed"]
    assert 0 < lo < 0.5 < hi < 1


def test_the_rate_population_on_the_committed_working_sample_adds_up():
    """On the committed pool: every sampled record is either in the working sample or listed as having left it,
    the verdicts add up to the study's own, and the run drawn from is the rate file's."""
    rate = E.load(E.RATE)
    S, R, H, synd, year = vu.load_pool()
    pool = ["syndicate_%s_%s" % (s, y) for s, y in zip(synd, year)]
    ex = E.load(E.EXPOSURE)
    run = ex.get("analysis_run_id_without_calibration", "run-without-calibration")
    out = E.rate_population(rate, pool, run)
    a = rate["A_sampled"]
    assert out["n_sampled"] == a["n_records"] == len(rate["final_verdicts"]["A"])
    assert out["n_in_current_working_sample"] + out["n_left_current_working_sample"] == out["n_sampled"]
    assert all(e["stem"] not in set(pool) for e in out["left_current_working_sample"])
    now = out["verdicts_in_current_working_sample"]
    gone = {"error": 0, "correct": 0, "undeterminable": 0}
    for e in out["left_current_working_sample"]:
        gone[e["verdict"]] += 1
    assert (now["error"] + gone["error"], now["correct"] + gone["correct"],
            now["undeterminable"] + gone["undeterminable"]) == (a["errors"], a["correct"], a["undeterminable"])
    assert out["drawn_from"]["exposure_results_run_id"] == rate["exposure_results_run_id"]
    assert out["current"] == {"exposure_results_run_id_without_calibration": run, "working_sample_n": len(pool)}


def test_the_manifest_step_writes_the_rate_population():
    src = io.open(os.path.join(HERE, "src", "error_rate_propagation.py"), encoding="utf-8").read()
    assert '"rate_population": rate_population(load(RATE), pool_stems, fit["loader_run_id_without_calibration"]),' in src
